[options]
db_host = db
db_port = 5432
db_user = odoo
db_name = lqa_panel_prod
dbfilter = ^lqa_panel_prod$
list_db = False
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
data_dir = /var/lib/odoo
proxy_mode = True
without_demo = all
workers = 2
max_cron_threads = 1
gevent_port = 8072
limit_memory_soft = 536870912
limit_memory_hard = 805306368
limit_request = 8192
limit_time_cpu = 600
limit_time_real = 1200
log_level = info
