{
    "name": "LQA Admin Panel",
    "version": "18.0.1.0.0",
    "category": "Sales",
    "summary": "Panel comercial para MercadoLibre y Automeli",
    "author": "Lo Quiero Aca",
    "license": "LGPL-3",
    "depends": ["base", "web"],
    "data": [
        "security/lqa_security.xml",
        "security/ir.model.access.csv",
        "views/panel_menu_views.xml",
        "views/panel_module_views.xml",
        "views/automeli_catalog_views.xml",
        "views/res_config_settings_views.xml",
        "views/panel_data.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "lqa_admin_panel/static/src/js/branding.js",
            "lqa_admin_panel/static/src/js/navigation.js",
            "lqa_admin_panel/static/src/js/dashboard.js",
            "lqa_admin_panel/static/src/js/mercadolibre_catalog.js",
            "lqa_admin_panel/static/src/js/mercadolibre_deleter.js",
            "lqa_admin_panel/static/src/js/mercadolibre_promotions.js",
            "lqa_admin_panel/static/src/js/automeli_catalog.js",
            "lqa_admin_panel/static/src/scss/dashboard.scss",
            "lqa_admin_panel/static/src/scss/mercadolibre_catalog.scss",
            "lqa_admin_panel/static/src/scss/mercadolibre_deleter.scss",
            "lqa_admin_panel/static/src/scss/mercadolibre_promotions.scss",
            "lqa_admin_panel/static/src/scss/automeli_catalog.scss",
            "lqa_admin_panel/static/src/scss/navbar.scss",
            "lqa_admin_panel/static/src/xml/dashboard.xml",
            "lqa_admin_panel/static/src/xml/mercadolibre_catalog.xml",
            "lqa_admin_panel/static/src/xml/mercadolibre_deleter.xml",
            "lqa_admin_panel/static/src/xml/mercadolibre_promotions.xml",
            "lqa_admin_panel/static/src/xml/automeli_catalog.xml",
            "lqa_admin_panel/static/src/xml/navbar.xml",
        ],
        "web.assets_frontend": [
            "lqa_admin_panel/static/src/js/branding.js",
        ],
    },
    "application": True,
    "installable": True,
}
