{
    "name": "LQA Admin Panel",
    "version": "18.0.1.0.20",
    "category": "Sales",
    "summary": "Panel interno para areas operativas de Lo Quiero Aca",
    "author": "Lo Quiero Aca",
    "license": "LGPL-3",
    "depends": ["base", "web"],
    "data": [
        "security/lqa_security.xml",
        "security/ir.model.access.csv",
        "data/mercadolibre_pricing_cron.xml",
        "data/retailers_pricing_cron.xml",
        "data/google_merchant_actions_cron.xml",
        "data/retailers_teams_notifications_cron.xml",
        "views/panel_menu_views.xml",
        "views/panel_module_views.xml",
        "views/automeli_catalog_views.xml",
        "views/res_config_settings_views.xml",
        "views/panel_data.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "lqa_admin_panel/static/src/js/branding.js",
            "lqa_admin_panel/static/src/js/navigation.js",
            "lqa_admin_panel/static/src/js/dashboard.js",
            "lqa_admin_panel/static/src/js/mercadolibre_catalog.js",
            "lqa_admin_panel/static/src/js/mercadolibre_selections.js",
            "lqa_admin_panel/static/src/js/mercadolibre_deleter.js",
            "lqa_admin_panel/static/src/js/mercadolibre_pricing.js",
            "lqa_admin_panel/static/src/js/mercadolibre_pricing_notifications.js",
            "lqa_admin_panel/static/src/js/mercadolibre_promotions.js",
            "lqa_admin_panel/static/src/js/automeli_catalog.js",
            "lqa_admin_panel/static/src/js/automeli_selections.js",
            "lqa_admin_panel/static/src/js/google_merchant_actions.js",
            "lqa_admin_panel/static/src/js/google_merchant_analytics.js",
            "lqa_admin_panel/static/src/js/accounting.js",
            "lqa_admin_panel/static/src/js/retailers.js",
            "lqa_admin_panel/static/src/js/retailers_catalog.js",
            "lqa_admin_panel/static/src/js/retailers_publisher.js",
            "lqa_admin_panel/static/src/js/retailers_publisher_execute.js",
            "lqa_admin_panel/static/src/js/retailers_publisher_tracking.js",
            "lqa_admin_panel/static/src/js/retailers_pricing.js",
            "lqa_admin_panel/static/src/js/retailers_orders.js",
            "lqa_admin_panel/static/src/js/user_management.js",
            "lqa_admin_panel/static/src/scss/dashboard.scss",
            "lqa_admin_panel/static/src/scss/mercadolibre_catalog.scss",
            "lqa_admin_panel/static/src/scss/mercadolibre_selections.scss",
            "lqa_admin_panel/static/src/scss/mercadolibre_deleter.scss",
            "lqa_admin_panel/static/src/scss/mercadolibre_pricing.scss",
            "lqa_admin_panel/static/src/scss/mercadolibre_promotions.scss",
            "lqa_admin_panel/static/src/scss/automeli_catalog.scss",
            "lqa_admin_panel/static/src/scss/automeli_selections.scss",
            "lqa_admin_panel/static/src/scss/google_merchant_actions.scss",
            "lqa_admin_panel/static/src/scss/google_merchant_analytics.scss",
            "lqa_admin_panel/static/src/scss/accounting.scss",
            "lqa_admin_panel/static/src/scss/retailers.scss",
            "lqa_admin_panel/static/src/scss/retailers_catalog.scss",
            "lqa_admin_panel/static/src/scss/retailers_publisher.scss",
            "lqa_admin_panel/static/src/scss/retailers_publisher_execute.scss",
            "lqa_admin_panel/static/src/scss/retailers_publisher_tracking.scss",
            "lqa_admin_panel/static/src/scss/retailers_pricing.scss",
            "lqa_admin_panel/static/src/scss/retailers_orders.scss",
            "lqa_admin_panel/static/src/scss/user_management.scss",
            "lqa_admin_panel/static/src/scss/navbar.scss",
            "lqa_admin_panel/static/src/scss/loading.scss",
            "lqa_admin_panel/static/src/xml/dashboard.xml",
            "lqa_admin_panel/static/src/xml/mercadolibre_catalog.xml",
            "lqa_admin_panel/static/src/xml/mercadolibre_selections.xml",
            "lqa_admin_panel/static/src/xml/mercadolibre_deleter.xml",
            "lqa_admin_panel/static/src/xml/mercadolibre_pricing.xml",
            "lqa_admin_panel/static/src/xml/mercadolibre_promotions.xml",
            "lqa_admin_panel/static/src/xml/automeli_catalog.xml",
            "lqa_admin_panel/static/src/xml/automeli_selections.xml",
            "lqa_admin_panel/static/src/xml/google_merchant_actions.xml",
            "lqa_admin_panel/static/src/xml/google_merchant_analytics.xml",
            "lqa_admin_panel/static/src/xml/accounting.xml",
            "lqa_admin_panel/static/src/xml/retailers.xml",
            "lqa_admin_panel/static/src/xml/retailers_catalog.xml",
            "lqa_admin_panel/static/src/xml/retailers_publisher.xml",
            "lqa_admin_panel/static/src/xml/retailers_publisher_execute.xml",
            "lqa_admin_panel/static/src/xml/retailers_publisher_tracking.xml",
            "lqa_admin_panel/static/src/xml/retailers_pricing.xml",
            "lqa_admin_panel/static/src/xml/retailers_orders.xml",
            "lqa_admin_panel/static/src/xml/user_management.xml",
            "lqa_admin_panel/static/src/xml/navbar.xml",
            "lqa_admin_panel/static/src/xml/loading.xml",
        ],
        "web.assets_frontend": [
            "lqa_admin_panel/static/src/js/branding.js",
        ],
    },
    "application": True,
    "installable": True,
}
